var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/interviews/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0us2dah._.js")
R.c("server/chunks/ssr/node_modules_08h8cko._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0s3v4~l.js")
R.c("server/chunks/ssr/[root-of-the-server]__0v9alue._.js")
R.c("server/chunks/ssr/[root-of-the-server]__090jxzh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__12ptu38._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/node_modules_next_dist_shared_lib_invariant-error_05dgpyz.js")
R.c("server/chunks/ssr/node_modules_next_dist_11dij6w._.js")
R.c("server/chunks/ssr/_0fj6_qn._.js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_interviews_page_actions_0lpiof6.js")
R.m(78332)
module.exports=R.m(78332).exports
